apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-practice
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/Kru2003/fleet-infra.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-practice
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-practice
